### ISSUE TITLE
update GUI

### ISSUE THREAD

**Issue by M4XMU3** [klml/msgsplit#7]
* set button on #getmessage underneath the text field
* update GUI to following CSS
`h1 {
text-transform: uppercase;
text-decoration: none;
}
h1:first-letter{
  color: #ffcc00;
}

a:active,:hover,:link,:visited {
text-decoration: none;
color: #333333;
}

.div{
background-color: #000;
}

.panel {
font: normal 18px arial;
text-decoration: none;
max-width: 1024px;
margin: auto;
}

.label,#message {
text-transform: uppercase;
}

#setmessage, #sendmessage, #getmessage {
border: 1px solid lightgrey;
border-radius: 5px;
background-color: rgb(224,224,224,0.5);
padding: 10px;
margin-top: 10px;
}
#getmessage {
display: none;
}

.input, #plaintext, #linktobob, #message {
width: 95%;
margin: 10px;
}

.button, #submitcipherserver, #getmessagebtn {
border-radius: 3px;
margin: 10px;
padding: 10px;
border: none;
background-color: #ffcc00; /#4CAF50/
}`

**Comment by klml** [comment]
@M4XMU3 plz PR

**Comment by M4XMU3** [comment]
solved by [PR 8](https://github.com/klml/msgsplit/pull/8)
